export {default as HomeLayout} from './HomeLayout';
export {default as Register} from './Register';
export {default as Login} from './Login';
export {default as Layout} from './Layout';
export {default as Error} from './Error';
export { default as DashboardLayout } from "./DashboardLayout";
export { default as Admin } from "./Admin";
export { default as AllJob } from "./AllJob";
export { default as AddJob } from "./AddJob";
export { default as EditJob } from "./EditJob";
export { default as Profile } from "./Profile";